<?php
/**
 * Created by PhpStorm.
 * User: Warlof Tutsimo
 * Date: 22/04/2018
 * Time: 11:48
 */

return [
    \Warlof\Seat\Migrator\Models\Killmail::class,
    \Warlof\Seat\Migrator\Models\KillmailAttacker::class,
    \Warlof\Seat\Migrator\Models\KillmailItem::class,
    \Warlof\Seat\Migrator\Models\CharacterCalendarEventDetail::class,
    \Warlof\Seat\Migrator\Models\CharacterAccountBalance::class,
    \Warlof\Seat\Migrator\Models\CharacterAffiliation::class,
    \Warlof\Seat\Migrator\Models\CharacterBookmark::class,
    \Warlof\Seat\Migrator\Models\CharacterTitle::class,
    \Warlof\Seat\Migrator\Models\CharacterImplant::class,
    \Warlof\Seat\Migrator\Models\CharacterJumpClone::class,
    \Warlof\Seat\Migrator\Models\CharacterSheet::class,
    \Warlof\Seat\Migrator\Models\CharacterShip::class,
    \Warlof\Seat\Migrator\Models\CharacterSkill::class,
    \Warlof\Seat\Migrator\Models\CharacterCorporationHistory::class,
    \Warlof\Seat\Migrator\Models\ChatChannelInfo::class,
    \Warlof\Seat\Migrator\Models\CharacterChatChannel::class,
    \Warlof\Seat\Migrator\Models\ChatChannelMember::class,
    \Warlof\Seat\Migrator\Models\ContactListCorporate::class,
    \Warlof\Seat\Migrator\Models\CharacterContactListLabel::class,
    \Warlof\Seat\Migrator\Models\CharacterContactList::class,
    \Warlof\Seat\Migrator\Models\CharacterContract::class,
    \Warlof\Seat\Migrator\Models\CharacterContractItem::class,
    \Warlof\Seat\Migrator\Models\CharacterIndustryJob::class,
    \Warlof\Seat\Migrator\Models\MailHeader::class,
    \Warlof\Seat\Migrator\Models\MailBody::class,
    \Warlof\Seat\Migrator\Models\MailingList::class,
    \Warlof\Seat\Migrator\Models\CharacterOrder::class,
    \Warlof\Seat\Migrator\Models\CharacterNotification::class,
    \Warlof\Seat\Migrator\Models\CharacterPlanet::class,
    \Warlof\Seat\Migrator\Models\CharacterPlanetLink::class,
    \Warlof\Seat\Migrator\Models\CharacterPlanetPin::class,
    \Warlof\Seat\Migrator\Models\CharacterPlanetRoute::class,
    \Warlof\Seat\Migrator\Models\CharacterResearch::class,
    \Warlof\Seat\Migrator\Models\CharacterSkillQueue::class,
    \Warlof\Seat\Migrator\Models\CharacterStanding::class,
    \Warlof\Seat\Migrator\Models\CharacterWalletJournal::class,
    \Warlof\Seat\Migrator\Models\CharacterWalletTransaction::class,
    // Corporation
    \Warlof\Seat\Migrator\Models\CorporationWalletBalance::class,
    \Warlof\Seat\Migrator\Models\CorporationAsset::class,
    \Warlof\Seat\Migrator\Models\CorporationBookmark::class,
    \Warlof\Seat\Migrator\Models\CorporationContact::class,
    \Warlof\Seat\Migrator\Models\CorporationContract::class,
    \Warlof\Seat\Migrator\Models\CorporationContractItem::class,
    \Warlof\Seat\Migrator\Models\CorporationCustomOffice::class,
    \Warlof\Seat\Migrator\Models\CorporationIndustryJob::class,
    \Warlof\Seat\Migrator\Models\CorporationOrder::class,
    \Warlof\Seat\Migrator\Models\CorporationMedal::class,
    \Warlof\Seat\Migrator\Models\CorporationIssuedMedal::class,
    \Warlof\Seat\Migrator\Models\CorporationMemberTracking::class,
    \Warlof\Seat\Migrator\Models\CorporationShareholder::class,
    \Warlof\Seat\Migrator\Models\CorporationHangarDivision::class,
    \Warlof\Seat\Migrator\Models\CorporationWalletDivision::class,
    \Warlof\Seat\Migrator\Models\CorporationSheet::class,
    \Warlof\Seat\Migrator\Models\CorporationStanding::class,
    \Warlof\Seat\Migrator\Models\CorporationStarbase::class,
    \Warlof\Seat\Migrator\Models\CorporationStarbaseDetail::class,
    \Warlof\Seat\Migrator\Models\CorporationTitle::class,
    \Warlof\Seat\Migrator\Models\CorporationWalletJournal::class,
    \Warlof\Seat\Migrator\Models\CorporationWalletTransaction::class,
];
